from .addAdvertisement import AddAdvertisement
from .addCoach import AddCoach
from .addExercise import AddExercise
from .addGroup import AddGroup
from .addInformation import AddInformation
from .addWorkout import AddWorkout
from .deleteMenu import DeleteMenu
from .editPassword import EditPassword
from .editSchedule import EditSchedule
