from .addAdmin import AddAdmin
from .addAdvertisement import AddAdvertisement
from .addCoach import AddCoach
from .addExercise import AddExercise
from .addGroup import AddGroup
from .addInformation import AddInformation
from .addLesson import AddLesson
from .addWorkout import AddWorkout
from .deleteMenu import DeleteMenu
from .editPassword import EditPassword
